AWSTemplateFormatVersion: "2010-09-09"
Description: "Create a VPC and Security Group"

Parameters:
  VPCCIDR:
    Type: String
    Default: 10.0.0.0/16
  SubnetCIDR:
    Type: String
    Default: 10.0.1.0/24

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true

  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow HTTP and SSH"
      VpcId: !Ref VPC

Outputs:
  SecurityGroupId:
    Description: "Security Group ID"
    Value: !Ref AppSecurityGroup
